// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6dVCSy2lys3iRh7c1CocRlFJhySubmg0',
    appId: '1:309492227864:web:2cac39f44b7b8a90c0c86d',
    messagingSenderId: '309492227864',
    projectId: 'smart-parking-d456d',
    authDomain: 'smart-parking-d456d.firebaseapp.com',
    storageBucket: 'smart-parking-d456d.firebasestorage.app',
    measurementId: 'G-DQDP8WJF81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0i1RA6sN13pstWik0K_5nsnKrXa9Vd2E',
    appId: '1:309492227864:android:cedf0c9f54d54e7ac0c86d',
    messagingSenderId: '309492227864',
    projectId: 'smart-parking-d456d',
    storageBucket: 'smart-parking-d456d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiMJMULf3ZF8rXhBJs_9QuvkHbYgoB3fM',
    appId: '1:309492227864:ios:54ce95abfd0f5882c0c86d',
    messagingSenderId: '309492227864',
    projectId: 'smart-parking-d456d',
    storageBucket: 'smart-parking-d456d.firebasestorage.app',
    iosBundleId: 'com.example.smartParkingAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiMJMULf3ZF8rXhBJs_9QuvkHbYgoB3fM',
    appId: '1:309492227864:ios:54ce95abfd0f5882c0c86d',
    messagingSenderId: '309492227864',
    projectId: 'smart-parking-d456d',
    storageBucket: 'smart-parking-d456d.firebasestorage.app',
    iosBundleId: 'com.example.smartParkingAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6dVCSy2lys3iRh7c1CocRlFJhySubmg0',
    appId: '1:309492227864:web:98c644de143872bcc0c86d',
    messagingSenderId: '309492227864',
    projectId: 'smart-parking-d456d',
    authDomain: 'smart-parking-d456d.firebaseapp.com',
    storageBucket: 'smart-parking-d456d.firebasestorage.app',
    measurementId: 'G-2CHY22RHDT',
  );
}
